//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMJ.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asociado
    {
        public int IdAsociado { get; set; }
        public int IdPromocion { get; set; }
        public string Descripcion { get; set; }
        public string Telefono { get; set; }
        public string NombreContacto { get; set; }
        public string Email { get; set; }
        public Nullable<int> Vigencia { get; set; }
        public string Plazo { get; set; }
        public string DVH { get; set; }
    
        public virtual Promocion Promocion { get; set; }
    }
}
