//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMJ.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int IdBitacora { get; set; }
        public int IdUsuario { get; set; }
        public string Descripcion { get; set; }
        public string FechayHora { get; set; }
        public string Criticidad { get; set; }
        public string DVH { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
