//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMJ.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Caja()
        {
            this.Caja_Producto = new HashSet<Caja_Producto>();
            this.Cliente = new HashSet<Cliente>();
            this.DetalleVentaPagos = new HashSet<DetalleVentaPagos>();
            this.Envio = new HashSet<Envio>();
        }
    
        public int IdCaja { get; set; }
        public int IdCliente { get; set; }
        public int IdProducto { get; set; }
        public int IdEnvio { get; set; }
        public int NroCaja { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> PrecintoEntrada { get; set; }
        public Nullable<int> PrecintoSalida { get; set; }
        public string EstadoCaja { get; set; }
        public string DVH { get; set; }
    
        public virtual Producto Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Caja_Producto> Caja_Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVentaPagos> DetalleVentaPagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Envio> Envio { get; set; }
    }
}
