//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMJ.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Compra = new HashSet<Compra>();
            this.Envio = new HashSet<Envio>();
            this.VentaPagos = new HashSet<VentaPagos>();
        }
    
        public int IdCliente { get; set; }
        public int IdFormulario { get; set; }
        public int IdCaja { get; set; }
        public int IdEnvio { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public Nullable<int> Telefono { get; set; }
        public int IdRol { get; set; }
        public string Estado { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string DatosPago { get; set; }
        public string DVH { get; set; }
        public Nullable<int> IdIdioma { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual Formulario Formulario { get; set; }
        public virtual Idioma Idioma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Envio> Envio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaPagos> VentaPagos { get; set; }
    }
}
