//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMJ.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int IdCompra { get; set; }
        public int IdCliente { get; set; }
        public int NroOC { get; set; }
        public string Detalle { get; set; }
        public string Descripcion { get; set; }
        public string DVH { get; set; }
        public Nullable<int> idVenta { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual VentaPagos VentaPagos { get; set; }
    }
}
