//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMJ.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVentaPagos
    {
        public int IdVenta { get; set; }
        public int Idcaja { get; set; }
        public Nullable<double> Precio { get; set; }
        public string Cantidad { get; set; }
        public string DVH { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual VentaPagos VentaPagos { get; set; }
    }
}
