//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMJ.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envio
    {
        public int IdEnvio { get; set; }
        public int IdCaja { get; set; }
        public string EstadoEnvio { get; set; }
        public string Descripcion { get; set; }
        public int NroEnvio { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string DVH { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
