//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMJ.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formulario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Formulario()
        {
            this.Cliente = new HashSet<Cliente>();
        }
    
        public int IdFormulario { get; set; }
        public int IdCliente { get; set; }
        public string Descripcion { get; set; }
        public string Sexo { get; set; }
        public string Estilo { get; set; }
        public string Color { get; set; }
        public string Calzado { get; set; }
        public string Remeras { get; set; }
        public string Camisas { get; set; }
        public string Pantalones { get; set; }
        public Nullable<double> Altura { get; set; }
        public Nullable<double> Peso { get; set; }
        public Nullable<double> Talle { get; set; }
        public string Objetivo { get; set; }
        public string DVH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Cliente { get; set; }
    }
}
