//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMJ.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traduccion
    {
        public int IdTraduccion { get; set; }
        public int IdIdioma { get; set; }
        public string Traduccion1 { get; set; }
        public string Descricion { get; set; }
        public string DVH { get; set; }
    
        public virtual Idioma Idioma { get; set; }
    }
}
